artifact_location: file:///C:/Users/Alex/Desktop/scikit/Bachelor/mlflow_tracking/mlflow_tracking/754383317655925649
creation_time: 1717171582084
experiment_id: '754383317655925649'
last_update_time: 1717171582084
lifecycle_stage: active
name: Evaluation-Active-Learning-Params
