on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          pip install -r requirements_extra.txt
          pip install pandas
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.DOCS_PAT }}
      - name: create experiment file
        run: |
          python .github/workflows/update_experiment.py
          shiny static-assets remove
          shinylive export src_shiny_app docs
          # git config --global user.name AlexanderBenz
          # git config --global user.email AlexanderBenz@users.noreply.github.com

          # git add -A
          # git commit -m "create shinylive docs"
          # git push
        - name: Deploy documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: docs
          target-folder: docs